### ISSUE TITLE
undefined local variable or method show_me_the_cookies

### ISSUE THREAD

**Issue by mois3x** [nruth/show_me_the_cookies#23]
Hey guys getting this error, im getting this error.  I did include `config.include ShowMeTheCookies, :type => :feature`

However when i call the method in an example just throw
````
  undefined local variable or method `show_me_the_cookies' for #<RSpec::ExampleGroups::DialogsAuth::WithOmniauthAndBrandClientId::....

````

im using new rails 4.1.1 and recent version of Rspec and Capybara

**Comment by nruth** [comment]
My setup is described in the readme and I'm afraid I don't know much more about it.
I'm closing this as it's an old ticket but if it's still a problem please let us know.
