### ISSUE TITLE
is there any way to set a signed cookie?

### ISSUE THREAD

**Issue by jasonfb** [nruth/show_me_the_cookies#31]
Just curious because I see no way to accessed the signed cookies

**Comment by nruth** [comment]
I haven't worked on that so not really sure. I'd imagine it isn't standardised, so depends on how signing is done by your application (framework)?

I'd instead add a url handler / controller / route / etc in your application just for testing, that lets you pass in the query params what you want it to write into the signed cookie. We do [something like that in the tests](https://github.com/nruth/show_me_the_cookies/blob/master/spec/app/set_cookie.rb). This reuses your application framework's signed cookies and avoids any extra integration work / maintenance.

I probably shouldn't have accepted the addition of setting cookies at all, as supporting unsigned but not signed seems like a poor API.

I won't be able to work on adding this feature, but if you find a good solution we could look at adding it.

**Comment by vasilakisfil** [comment]
Here is how I did it in Rails 5 with Rspec, in a `before do` action:

```ruby
      my_jar = ActionDispatch::Request.new(Rails.application.env_config).cookie_jar
      my_jar.signed['key'] = 'A value'
      create_cookie('key', my_jar['key'])
```

Basically you sign the cookie yourself, and you write it in the jar.

**Comment by vasilakisfil** [comment]
I think it should go to the Readme. It's Rails-relevant but still I think it would help people.

**Comment by nruth** [comment]
@vasilakisfil would you like to PR that addition or can I do it?
