### ISSUE TITLE
create_cookie breaks the rails sessions

### ISSUE THREAD

**Issue by 3den** [nruth/show_me_the_cookies#39]
Hi, I am currently struggling with a very strange issue. If I create a cookie on a before block the flash messages do not persist. If i just comment out the line that use `create_cookie` it that same tests passes. Below is an example:

```ruby
# controller create if save is successful
 redirect_to redirect_path, notice: "Something was successfully saved"

# capybara test
... fill in the form and click on save
# the redirect works and the item is created but there is not flash message if create_cookie was used
expect(page).to have_content("Content was successfully created.")
```

I added several `puts` statements to debug and noticed that the flash does not persist across requests when the cookie was set.

**Comment by nruth** [comment]
If you're writing into the rails session cookie with these test helpers I guess it's been considered corrupted and thrown away by Rails, because of the tamper-proof / encryption protection it has?

**Comment by 3den** [comment]
Hi @nruth thanks for the quick repply, this gem is working fine the problem was just becuse a controller was reseting the session, but i already fixed that problem. 

This gem is pretty awesome thanks for publising :+1:
