### ISSUE TITLE
Configure ShowMeTheCookies at the application level?

### ISSUE THREAD

**Issue by mjsommer** [nruth/show_me_the_cookies#43]
I would like to use ShowMeTheCookies inside the Rails application as a whole, and not just within Rspec. Can you please show how it would be configured at the application level, for example:

```
module ApplicationHelper
  Application.configure do |config|
    config.include ShowMeTheCookies, :type => :feature
  end
end
```
This is not working, and without it, I get:

`undefined local variable or method show_me_the_cookies
`

Thank you.

**Comment by nruth** [comment]
Hi 
This is a testing tool used to look at client cookies for debugging.
 If you are working on rails it sounds like you are in the server and should look at the rails or rack cookie api instead of needing this?

**Comment by mjsommer** [comment]
Capybara is primarily a testing tools as well, but can be used elsewhere. Since ShowMeTheCookies is your gem, I just thought you would know how to configure it, for the app as a whole?

**Comment by nruth** [comment]
OK that makes sense. I guess it should be possible if you look at what that module does and where else you could/should include it, probably into the context you're using Capybara in without RSpec, but it's not something I'll be able to put time into supporting/investigating. Sorry!

I wouldn't recommend using this gem as a main application dependency as although it's fairly small, it's not actively maintained, and you can get the same things by using the APIs directly if you've decided on a particular capybara driver to run in production.

**Comment by mjsommer** [comment]
Thanks, I am using two:

```
Capybara::Session.new(:poltergeist) #Headless
Capybara::Session.new(:selenium) #Visual

```
Which API would you recommend, to get and set the cookies? Basically, I am storing them in the session, and the pulling them back.

Thanks again!

**Comment by nruth** [comment]
I guess this is too late now (sorry), but: take a look in https://github.com/nruth/show_me_the_cookies/tree/master/lib/show_me_the_cookies/adapters and the api docs (or implementation code) for the driver you want to use. Webdriver (selenium) is probably the best documented (though can be hard to hunt down the right bit), and now has headless support, so I'd suggest starting there.
For more detailed guidance there might be something in https://seleniumguidebook.com/ on cookies, but I've not checked and wouldn't be surprised if it's missing (as it tends to pretend capybara doesn't exist and re-solves the same problems).
