### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by henrik** [nruth/show_me_the_cookies#46]
How would you feel about introducing a changelog? The major version just changed and I wanted to verify there were no breaking changes.

For now I looked at https://github.com/nruth/show_me_the_cookies/compare/v3.1.0...v4.0.0, but crafting that URL took a little effort.

**Comment by nruth** [comment]
I'll add one. For now I wrote it up in the release/tag commit comments: https://github.com/nruth/show_me_the_cookies/commit/cc0a1106d9cb00827aeda3301f5b75d6d10e80ba

**Comment by henrik** [comment]
Ah, I missed that one. Thank you!
